Extracting data from resume using Resume Parser Library</h2>

In [ ]:
%%capture
!pip install nltk
!pip install spacy==2.3.5
!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz

In [ ]:
%%capture
!apt-get -qq install -y graphviz && pip install pyresparser
!apt-get -qq install -y graphviz && pip install python_docx

In [ ]:
import numpy as np
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from pyresparser import ResumeParser
import os
from docx import Document

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# %%capture
# !git clone https://github.com/jsvine/pdfplumber.git

In [ ]:
# %%capture
# !cd pdfplumber; pip install .; cd ..

In [ ]:
# %%capture
# !pip3 install pdfplumber

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# JOB SEEKER

**Upload Resume Module**

In [ ]:
from google.colab import files
uploaded = files.upload()
# type(uploaded)

Saving 10810913.pdf to 10810913.pdf


In [ ]:
type(uploaded)
next(iter(uploaded))

'10810913.pdf'

In [ ]:
# save resume file in drive

import shutil
colab_link = "/content/"+next(iter(uploaded))
gdrive_link = "/content/drive/MyDrive/Colab/AI_project/resumes"
filed = shutil.copy(colab_link, gdrive_link)

In [ ]:
try:
    doc = Document()
    # if file is in .txt format
    with open(filed, 'r') as file:
        doc.add_paragraph(file.read())
    doc.save("text.docx")
    data = ResumeParser('text.docx').get_extracted_data()
except:
    data = ResumeParser(filed).get_extracted_data()

/usr/local/lib/python3.8/dist-packages/spacy/util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)


In [ ]:
print(type(data))

# listd1 = []
# for i in data.keys():
#   listd1.append(i)
#   # print(i+",", end='')

# listd1

<class 'dict'>


In [ ]:
print(data)

{'name': 'Harsha Himani', 'email': 'himaniftb@gmail.com', 'mobile_number': '9182371544', 'skills': ['Policies', 'Engagement', 'Agile', 'Engineering', 'Plan', 'Scrum', 'Analytical', 'Payments', 'Testing', 'Process', 'Analysis', 'Windows', 'Database', 'Administration', 'Programming', 'Computer science', 'System'], 'college_name': None, 'degree': ['B.Tech (Bachelor of Technology)'], 'designation': ['System Engineer'], 'experience': ['System Engineer', 'Infosys', 'Apr 2021 - Present (1 year 10 months)', 'System Engineer', 'Project Name- McCamish System About Client:', 'John Hancock Life Insurance Company, U.S.A. a is Boston-based insurance company. Company', 'provides', 'life insurance, mutual fund long-term care, retirement plan service, and institutional investment', 'products.', 'Size of Engagement : More than 100 resources', 'Project Title : John Hancock; Team Size :20', 'Environment(Technical): Progress OpenEdge 11.x, Round Table.', 'About Project:', 'VPAS is a progress application th

In [ ]:
# d1 ={}
counter =0
for key, val in data.items():
    print(key," : ",val)
    # d1.update( {key : listd1[counter]} )
    # counter = counter+1

name  :  Harsha Himani
email  :  himaniftb@gmail.com
mobile_number  :  9182371544
skills  :  ['Policies', 'Engagement', 'Agile', 'Engineering', 'Plan', 'Scrum', 'Analytical', 'Payments', 'Testing', 'Process', 'Analysis', 'Windows', 'Database', 'Administration', 'Programming', 'Computer science', 'System']
college_name  :  None
degree  :  ['B.Tech (Bachelor of Technology)']
designation  :  ['System Engineer']
experience  :  ['System Engineer', 'Infosys', 'Apr 2021 - Present (1 year 10 months)', 'System Engineer', 'Project Name- McCamish System About Client:', 'John Hancock Life Insurance Company, U.S.A. a is Boston-based insurance company. Company', 'provides', 'life insurance, mutual fund long-term care, retirement plan service, and institutional investment', 'products.', 'Size of Engagement : More than 100 resources', 'Project Title : John Hancock; Team Size :20', 'Environment(Technical): Progress OpenEdge 11.x, Round Table.', 'About Project:', 'VPAS is a progress application that man

In [ ]:
from csv import DictWriter
 
# list of column names
field_names = data.keys()
 
# Open CSV file in append mode
# Create a file object for this file
with open('/content/drive/MyDrive/Colab/AI_project/resumes/resume_dataset.csv', 'a') as f_object:
  # TO ADD COLUMNS NAMES
    # dictwriter_object = DictWriter(f_object, fieldnames=field_names)
    # dictwriter_object.writerow(d1)
    
    # Pass the file object and a list of column names to DictWriter()
    # You will get a object of DictWriter
    dictwriter_object = DictWriter(f_object, fieldnames=field_names)
 
    # Pass the dictionary as an argument to the Writerow()
    dictwriter_object.writerow(data)
 
    # Close the file object
    f_object.close()

In [ ]:
df =pd.read_csv('/content/drive/MyDrive/Colab/AI_project/resumes/resume_dataset.csv')
df.tail()

name                            email mobile_number  \
17        Lavanya  lavanya.adhinarayanan@gmail.com     988403855   
18            NaN                              NaN           NaN   
19          Rohan               rohan230@gmail.com      011-2014   
20          Aneet           aneetatomy23@gmail.com    8129945395   
21  Harsha Himani              himaniftb@gmail.com    9182371544   

                                               skills  \
17  ['Sports', 'Engineering', 'Scrum', 'Payments',...   
18                                                NaN   
19  ['Ai', 'Content', 'Mysql', 'C', 'Oracle', 'Min...   
20  ['Engineering', 'Windows', 'Java', 'Social med...   
21  ['Policies', 'Engagement', 'Agile', 'Engineeri...   

                                college_name  \
17  Dayal Singh College, University of Delhi   
18                                       NaN   
19                                       NaN   
20                           NSIT, New Delhi   
21                                       NaN   

                                 degree          designation  \
17                           B.Sc. Hons                  NaN   
18                                  NaN                  NaN   
19                       ['BCA', 'MCA']                  NaN   
20           B.Tech (Computer Science)                   NaN   
21  ['B.Tech (Bachelor of Technology)']  ['System Engineer']   

                                           experience company_names  \
17  ['▪', '▪ Worked with Insoft.com Private Ltd, C...           NaN   
18                                                NaN           NaN   
19  ['ESAF CO-OPERATIVE', ':IT Assistant :  2019 –...           NaN   
20  ['PageMe Consultancy [Digital Marketing Analys...           NaN   
21  ['System Engineer', 'Infosys', 'Apr 2021 - Pre...   ['Infosys']   

    no_of_pages  total_experience  
17          9.0              0.00  
18          NaN               NaN  
19          3.0              0.00  
20          2.0              0.25  
21          2.0              1.92

Skill extraction from job description

In [ ]:
stopw  = set(stopwords.words('english'))
type(stopw)
# stopw

set

In [ ]:
all_jobs_df =pd.read_csv('https://raw.githubusercontent.com/pik1989/HRAnalytics-Project/main/job_final.csv') 
print("Size of the data set : ", all_jobs_df.shape)
all_jobs_df.head()

Size of the data set :  (1924, 6)


Unnamed: 0                                                url  \
0           0  https://www.glassdoor.co.in/partner/jobListing...   
1           1  https://www.glassdoor.co.in/partner/jobListing...   
2           2  https://www.glassdoor.co.in/partner/jobListing...   
3           3  https://www.glassdoor.co.in/partner/jobListing...   
4           4  https://www.glassdoor.co.in/partner/jobListing...   

                                            Position  \
0                        Software Testing Internship   
1                          Embedded Software Testing   
2  Senior Engineer - Software Testing (Bangalore ...   
3                          Software Testing Engineer   
4           CIEL/SEL/1888: Software testing Engineer   

                         Company      Location  \
0  Smart Food Safe Solutions Inc   – Bengaluru   
1                       Mobiveil   – Bengaluru   
2     Open Systems International   – Bengaluru   
3                Bloom Solutions   – Bengaluru   
4               CIEL HR Services   – Bengaluru   

                                     Job_Description  
0  About the company:\nSmart Food Safe Solutions ...  
1  Location : Bangalore\nExperience : 4+ Years\n\...  
2  Open Systems International, Inc. (OSI) www.osi...  
3  About the Job\n\nSoftware Testing Engineer\n\n...  
4  Location: Bangalore\nExperience: 3 to 6Years\n...

In [ ]:
all_jobs_df['Job_Description']

Size of the data set :  (1924, 6)


0       About the company:\nSmart Food Safe Solutions ...
1       Location : Bangalore\nExperience : 4+ Years\n\...
2       Open Systems International, Inc. (OSI) www.osi...
3       About the Job\n\nSoftware Testing Engineer\n\n...
4       Location: Bangalore\nExperience: 3 to 6Years\n...
                              ...                        
1919    Skills and Qualifications:\n\n2+ Years of expe...
1920    Job ID : TH10519_13189\n\nPosted on: 29th of M...
1921    Job Description\nWe spend 90 percent of\n\nour...
1922    (Job Number: 1905027)\n\nJob Title – Web Dev...
1923    We marry design and engineering language in wa...
Name: Job_Description, Length: 1924, dtype: object

In [ ]:
print(all_jobs_df.columns)
all_jobs_df.rename(columns = {'Unnamed: 0':'index'}, inplace = True)

Index(['Unnamed: 0', 'url', 'Position', 'Company', 'Location',
       'Job_Description'],
      dtype='object')


In [ ]:
all_jobs_df = all_jobs_df.dropna()
print("Size of the data set : ", all_jobs_df.shape)

Size of the data set :  (1923, 6)


In [ ]:
import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm") 

def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    
    return " ".join(filtered_tokens) 

In [ ]:
# print(all_jobs_df['Job_Description'][0])
# print("")
# print("")
# print("-----------------------------------AFTER PROCESSING------------------------------------")
# print("Processed Data :",end='')
# processes_jobdes = preprocess(all_jobs_df['Job_Description'][0])
# print(processes_jobdes)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer

# vtest = CountVectorizer()
# vtest = CountVectorizer(ngram_range=(1,2))
# vtest.fit(["I am a robot who loves to play with people"])
# print("Length of frequency matrix :",len(vtest.vocabulary_))
# count = 1
# print(" ")
# for key, val in vtest.vocabulary_.items():
#   if count%5:
#     print(key,":", val, end=" ")
#   else:
#     print(key,":", val)
#   count = count+1
# tf_count = vtest.transform(["I am a robot"])
# print(" ")
# print("Count Vector for sentence 'I am a robot' :")
# tf_count.toarray()

Length of frequency matrix : 15
 
am : 0 robot : 7 who : 11 loves : 2 to : 9
play : 5 with : 13 people : 4 am robot : 1 robot who : 8
who loves : 12 loves to : 3 to play : 10 play with : 6 with people : 14
 
Count Vector for sentence 'I am a robot' :


array([[1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# v = CountVectorizer(ngram_range=(1,2))
# v.fit([processes_jobdes])
# print(type(v.vocabulary_))
# print(len(v.vocabulary_))
# v.vocabulary_

In [ ]:
all_jobs_df['test']=all_jobs_df['Job_Description'].apply(preprocess)
all_jobs_df['test']

0       company \n Smart Food Safe Solutions Inc. food...
1       location bangalore \n experience 4 + year \n\n...
2       Open Systems International Inc. OSI www.osii.c...
3       Job \n\n software Testing Engineer \n\n\n Job ...
4       location bangalore \n experience 3 6year \n sk...
                              ...                        
1919    skill qualification \n\n 2 + year experience \...
1920    Job ID th10519_13189 \n\n post 29th 2019Job Po...
1921    Job Description \n spend 90 percent \n\n life ...
1922    Job number 1905027 \n\n Job Title †Web Devel...
1923    marry design engineering language way produce ...
Name: test, Length: 1923, dtype: object

In [ ]:
%%capture
!pip install ftfy

In [ ]:
import re

from ftfy import fix_text

def string_process(string, n=2):
    string = fix_text(string) # fix text
    string = string.encode("ascii", errors="ignore").decode() #remove non ascii chars 
    chars_to_remove = [")","(",".","|","[","]","{","}","'"]
    rx = '[' + re.escape(''.join(chars_to_remove)) + ']'
    string = re.sub(rx, '', string)
    string = string.replace('&', 'and')
    string = string.replace('\n', ' ')
    string = string.replace(',', ' ')
    string = string.replace('-', ' ')
    string = string.title()                       # normalise case - capital at start of each word
    string = re.sub(' +',' ',string).strip()      # get rid of multiple spaces and replace with a single
    string = ' '+ string +' '                     # pad names for ngrams...
    string = re.sub(r'[,-./]|\sBD',r'', string)
    string = string.lower()
    return string

In [ ]:
# string_process(all_jobs_df['Job_Description'][2])

In [ ]:
all_jobs_df['test']=all_jobs_df['Job_Description'].apply(string_process)
all_jobs_df['test']

0        about the company: smart food safe solutions ...
1        location : bangalore experience : 4+ years jo...
2        open systems international inc osi wwwosiicom...
3        about the job software testing engineer job d...
4        location: bangalore experience: 3 to 6years s...
                              ...                        
1919     skills and qualifications: 2+ years of experi...
1920     job id : th10519_13189 posted on: 29th of may...
1921     job description we spend 90 percent of our li...
1922     job number: 1905027 job title web developer u...
1923     we marry design and engineering language in w...
Name: test, Length: 1923, dtype: object

In [ ]:
# print(data['skills'])

data_lower = []
for s in data['skills']:
    data_lower.append(s.lower())

jobseeker_skills = " "
jobseeker_skills = jobseeker_skills.join(data_lower)
j=1
for i in jobseeker_skills:
  if j%40:
    print(i, end='')
  else:
    print(i)
  j = j+1

affiliate visual content html python com
puter science mobile android website pre
sentation mysql php c++ java xml

In [ ]:
v = CountVectorizer()

v = CountVectorizer(ngram_range=(1,2))
v.fit([jobseeker_skills])
print(type(v.vocabulary_))
print(len(v.vocabulary_))
v.vocabulary_

<class 'dict'>
29


{'affiliate': 0,
 'visual': 24,
 'content': 6,
 'html': 8,
 'python': 20,
 'computer': 4,
 'science': 22,
 'mobile': 12,
 'android': 2,
 'website': 26,
 'presentation': 18,
 'mysql': 14,
 'php': 16,
 'java': 10,
 'xml': 28,
 'affiliate visual': 1,
 'visual content': 25,
 'content html': 7,
 'html python': 9,
 'python computer': 21,
 'computer science': 5,
 'science mobile': 23,
 'mobile android': 13,
 'android website': 3,
 'website presentation': 27,
 'presentation mysql': 19,
 'mysql php': 15,
 'php java': 17,
 'java xml': 11}

In [ ]:
tf_count = v.transform(all_jobs_df['test'])
tf_ud = tf_count.toarray()
print(type(tf_count))
print(tf_ud.shape)
print(tf_ud)

<class 'scipy.sparse.csr.csr_matrix'>
(1923, 233)
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.neighbors import NearestNeighbors

nbrs = NearestNeighbors(n_neighbors=10, n_jobs=-1).fit(tf_count)

In [ ]:
def getNearestN(query):
  q_tf_count = v.transform(query)
  distances, indices = nbrs.kneighbors(q_tf_count)
  return distances, indices

In [ ]:
distances, indices = getNearestN([jobseeker_skills])

In [ ]:
print("Distances          ", "Indices")
for i in range(1,len(distances[0])):
  print(distances[0][i],"    ", indices[0][i])

Distances           Indices
4.58257569495584      1426
4.58257569495584      710
4.58257569495584      1524
4.69041575982343      1592
4.69041575982343      1799
4.69041575982343      1779
4.69041575982343      1780
4.795831523312719      500
4.795831523312719      1099


In [ ]:
type(indices)
for i in indices:
    rec_jobs = all_jobs_df[['Position', 'Company','Location']].iloc[i] 
rec_jobs

Position               Company  \
1900                              Full Stack Developer  Indian Angel network   
1427                               Front-end Developer                Toolyt   
710                   Staff Engineer, Data Engineering       Western Digital   
1525                           Full stack UI developer              Netskope   
1593                               Front-End Developer               Greytip   
1800                         Front End Developer - F&R             Refinitiv   
1780  Software Engineering - Senior Java Web Developer           J.P. Morgan   
1781                            UI Developer (Angular)             Bengaluru   
500           .Net/Sitecore Senior Solutions Architect            Rightpoint   
1100                                     Data Engineer             Noodle.ai   

            Location  
1900       Bengaluru  
1427       Bengaluru  
710    – Bengaluru  
1525       Bengaluru  
1593       Bengaluru  
1800       Bengaluru  
1780       Bengaluru  
1781       Bengaluru  
500         – Jaipur  
1100       Bengaluru

**Using TF_IDF vectorizer**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import re

In [ ]:
vtest = TfidfVectorizer()
vtest = TfidfVectorizer(ngram_range=(1,2))
vtest.fit(["I am a robot who loves to play with people"])
print("Length of frequency matrix :",len(vtest.vocabulary_))
count = 1
print(" ")
for key, val in vtest.vocabulary_.items():
  if count%5:
    print(key,":", val, end=" ")
  else:
    print(key,":", val)
  count = count+1
tf_count = vtest.transform(["I am a robot"])
print(" ")
print("Count Vector for sentence 'I am a robot' :")
tf_count.toarray()

Length of frequency matrix : 15
 
am : 0 robot : 7 who : 11 loves : 2 to : 9
play : 5 with : 13 people : 4 am robot : 1 robot who : 8
who loves : 12 loves to : 3 to play : 10 play with : 6 with people : 14
 
Count Vector for sentence 'I am a robot' :


array([[0.57735027, 0.57735027, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [ ]:
vectorizer = TfidfVectorizer(min_df=1, ngram_range=(1, 2))
vectorizer.fit([jobseeker_skills])
print(type(vectorizer.vocabulary_))
print(len(vectorizer.vocabulary_))
vectorizer.vocabulary_

<class 'dict'>
29


{'affiliate': 0,
 'visual': 24,
 'content': 6,
 'html': 8,
 'python': 20,
 'computer': 4,
 'science': 22,
 'mobile': 12,
 'android': 2,
 'website': 26,
 'presentation': 18,
 'mysql': 14,
 'php': 16,
 'java': 10,
 'xml': 28,
 'affiliate visual': 1,
 'visual content': 25,
 'content html': 7,
 'html python': 9,
 'python computer': 21,
 'computer science': 5,
 'science mobile': 23,
 'mobile android': 13,
 'android website': 3,
 'website presentation': 27,
 'presentation mysql': 19,
 'mysql php': 15,
 'php java': 17,
 'java xml': 11}

In [ ]:
tfidf = vectorizer.transform(all_jobs_df['test'])
print(type(tfidf))
tfidf_arr = tfidf.toarray()
print(tfidf_arr.shape)

print(vectorizer.get_feature_names_out())
print(tfidf.indices)
print(tfidf_arr)

<class 'scipy.sparse.csr.csr_matrix'>
(1923, 29)
['affiliate' 'affiliate visual' 'android' 'android website' 'computer'
 'computer science' 'content' 'content html' 'html' 'html python' 'java'
 'java xml' 'mobile' 'mobile android' 'mysql' 'mysql php' 'php' 'php java'
 'presentation' 'presentation mysql' 'python' 'python computer' 'science'
 'science mobile' 'visual' 'visual content' 'website'
 'website presentation' 'xml']
[22  5  4 ... 10  6 10]
[[0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.2236068 0.        0.2236068]
 [0.        0.        0.        ... 0.        0.        0.       ]]


In [ ]:
nbrs = NearestNeighbors(n_neighbors=10, n_jobs=-1).fit(tfidf)

In [ ]:
def getNearestN(query):
  q_tf_count = vectorizer.transform(query)
  distances, indices = nbrs.kneighbors(q_tf_count)
  return distances, indices

In [ ]:
jobseeker_skills

'affiliate visual content html python computer science mobile android website presentation mysql php c++ java xml'

In [ ]:
distances, indices = getNearestN([jobseeker_skills])

In [ ]:
print("Distances            ", "Indices")
for i in range(1,len(distances[0])):
  print(distances[0][i],"    ", indices[0][i])

Distances             Indices
0.9744478113897219      710
0.9744478113897219      1426
0.9744478113897219      1524
0.9960890925411551      1780
0.9960890925411551      1779
0.9999999999999998      686
0.9999999999999998      667
0.9999999999999998      655
0.9999999999999998      703


In [ ]:
type(indices)
for i in indices:
    rec_jobs = all_jobs_df[['Position', 'Company','Location']].iloc[i] 
rec_jobs

Position               Company  \
1900                               Full Stack Developer  Indian Angel network   
710                    Staff Engineer, Data Engineering       Western Digital   
1427                                Front-end Developer                Toolyt   
1525                            Full stack UI developer              Netskope   
1781                             UI Developer (Angular)             Bengaluru   
1780   Software Engineering - Senior Java Web Developer           J.P. Morgan   
686   Lead - Global Advanced Analytics Data Scientist-2                Diageo   
667                                        Data Analyst             SmartCoin   
655   Data Scientist (3-8 Years) for a Leading Softw...                 Zyoin   
703                                   Big Data Engineer                 Ganit   

            Location  
1900       Bengaluru  
710    – Bengaluru  
1427       Bengaluru  
1525       Bengaluru  
1781       Bengaluru  
1780       Bengaluru  
686    – Bengaluru  
667    – Bengaluru  
655    – Bengaluru  
703    – Bengaluru

# JOB RECRUITOR


UPLOAD JOB DETAILS

In [ ]:
job_details = {}

job_details['company_name'] = input("Enter the company name: ")
job_details['job_title']  = input("Enter the job title: ")
job_details['job_des'] = input("Enter the job description: ")
job_details['job_location'] = input("Enter the job location: ")
job_details['exp_req']= input("Enter the experience required from candidate: ")
job_details['edu_req']= input("Enter the educational qualifications required: ")
job_details['cert_req']= input("Enter the exra certifications required (optional): ")

KeyboardInterrupt: ignored

APPEND JOB DETAILS

In [ ]:
from csv import DictWriter
 
field_names = job_details.keys()
 
with open('/content/drive/MyDrive/AI_project/job_sample/job_dataset.csv', 'a') as f_object:
  # TO ADD COLUMNS NAMES
    # dictwriter_object = DictWriter(f_object, fieldnames=field_names)
    # dictwriter_object.writerow(d1)
    
    # Pass the file object and a list of column names to DictWriter()
    # You will get a object of DictWriter
    dictwriter_object = DictWriter(f_object, fieldnames=field_names)
 
    # Pass the dictionary as an argument to the Writerow()
    dictwriter_object.writerow(job_details)
 
    # Close the file object
    f_object.close()

In [ ]:
# listd1 = []
# for i in job_details.keys():
#   listd1.append(i)
#   # print(i+",", end='')

# listd1

# d1 ={}
# counter =0
# for key, val in job_details.items():
#     print(key," : ",val)
#     d1.update( {key : listd1[counter]} )
#     counter = counter+1

# d1

In [ ]:
jobs =pd.read_csv('/content/drive/MyDrive/Colab/AI_project/job_sample/jobs_dataset.csv')
jobs.tail()

Skill extraction from job description

In [ ]:
resumes =pd.read_csv('/content/drive/MyDrive/Colab/AI_project/resumes/resume_dataset.csv') 
resumes.tail()

name                            email mobile_number  \
17  Lavanya  lavanya.adhinarayanan@gmail.com     988403855   
18      NaN                              NaN           NaN   
19    Rohan               rohan230@gmail.com      011-2014   
20    Aneet           aneetatomy23@gmail.com    8129945395   
21   Himani              himaniftb@gmail.com    9182371544   

                                               skills  \
17  ['Sports', 'Engineering', 'Scrum', 'Payments',...   
18                                                NaN   
19  ['Ai', 'Content', 'Mysql', 'C', 'Oracle', 'Min...   
20  ['Engineering', 'Windows', 'Java', 'Social med...   
21  ['Policies', 'Engagement', 'Agile', 'Engineeri...   

                                college_name  \
17  Dayal Singh College, University of Delhi   
18                                       NaN   
19                                       NaN   
20                           NSIT, New Delhi   
21                                       NaN   

                                 degree          designation  \
17                           B.Sc. Hons                  NaN   
18                                  NaN                  NaN   
19                       ['BCA', 'MCA']                  NaN   
20            B.Tech (Computer Science)                  NaN   
21  ['B.Tech (Bachelor of Technology)']  ['System Engineer']   

                                           experience company_names  \
17  ['▪', '▪ Worked with Insoft.com Private Ltd, C...           NaN   
18                                                NaN           NaN   
19  ['ESAF CO-OPERATIVE', ':IT Assistant :  2019 –...           NaN   
20  ['PageMe Consultancy [Digital Marketing Analys...           NaN   
21  ['System Engineer', 'Infosys', 'Apr 2021 - Pre...   ['Infosys']   

    no_of_pages  total_experience  
17          9.0              0.00  
18          NaN               NaN  
19          3.0              0.00  
20          2.0              0.25  
21          2.0              1.92

In [ ]:
resumes['skills']

0     ['Engineering', 'Java', 'Tensorflow', 'Researc...
1     ['Digital marketing', 'Excel', 'Photoshop', 'P...
2     ['Engineering', 'Java', 'Database', 'Documenta...
3     ['Php', 'Computer science', 'Java', 'Website',...
4                             ['English', 'Email', 'C']
5     ['Data analytics', 'Seaborn', 'Matplotlib', 'P...
6     ['Mysql', 'Purchasing', 'Windows', 'Tableau', ...
7     ['Design', 'Certification', 'Engineering', 'Pr...
8     ['Policies', 'Updates', 'Mysql', 'Engineering'...
9     ['Java', 'Email', 'Html', 'Technical', 'Newspa...
10    ['Salesforce', 'Finance', 'Mis', 'Seo', 'Websi...
11    ['Php', 'Training', 'Mysql', 'Java', 'Engineer...
12    ['Mysql', 'Vendors', 'Engineering', 'Distribut...
13    ['Excel', 'Mysql', 'Engineering', 'Analytics',...
14    ['C', 'Html', 'Technical', 'Javascript', 'Engl...
15    ['Mechanical engineering', 'Reporting', 'Resea...
16    ['Scripting', 'Java', 'Oracle', 'Windows', 'Sq...
17    ['Sports', 'Engineering', 'Scrum', 'Paymen

In [ ]:
print(resumes.columns)
# all_jobs_df.rename(columns = {'Unnamed: 2':'index'}, inplace = True)

Index(['name', 'email', 'mobile_number', 'skills', 'college_name', 'degree',
       'designation', 'experience', 'company_names', 'no_of_pages',
       'total_experience'],
      dtype='object')


In [ ]:
# jobs_df = jobs.dropna()
resumes = resumes[resumes['skills'].notna()]
print("Size of the data set : ", resumes.shape)

Size of the data set :  (21, 11)


In [ ]:
resumes['test']=resumes['skills'].apply(preprocess)
resumes['test']

0     engineering Java Tensorflow research Python Op...
1     Digital marketing Excel Photoshop Python marke...
2     engineering Java Database documentation softwa...
3     Php computer science Java website Presentation...
4                                       English email C
5     datum analytic Seaborn Matplotlib Pandas Pytho...
6     Mysql purchase Windows Tableau Linux schedule ...
7     design certification engineering process email...
8     policy update Mysql engineering forecast query...
9     Java email Html technical newspaper English C+...
10    salesforce Finance Mis Seo website design Crm ...
11    Php training Mysql Java engineering proposal t...
12    Mysql vendor engineering distribution query Cs...
13    Excel Mysql engineering analytic sale Python t...
14    C Html technical Javascript English administra...
15    mechanical engineering report research technic...
16    Scripting Java Oracle Windows Sql English Css ...
17    sport engineering Scrum payment Erp Window

In [ ]:
resumes['test']=resumes['skills'].apply(string_process)
resumes['test']

0      engineering java tensorflow research python o...
1      digital marketing excel photoshop python mark...
2      engineering java database documentation softw...
3      php computer science java website presentatio...
4                                      english email c 
5      data analytics seaborn matplotlib pandas pyth...
6      mysql purchasing windows tableau linux schedu...
7      design certification engineering process emai...
8      policies updates mysql engineering forecastin...
9      java email html technical newspaper english c...
10     salesforce finance mis seo website design crm...
11     php training mysql java engineering proposal ...
12     mysql vendors engineering distribution querie...
13     excel mysql engineering analytics sales pytho...
14     c html technical javascript english administr...
15     mechanical engineering reporting research tec...
16     scripting java oracle windows sql english css...
17     sports engineering scrum payments erp win

RECOMMENDING TOP 3 JOB-SEEKERS FOR A JOB

In [ ]:
test_job = jobs.iloc[0]
type(test_job)

pandas.core.series.Series

In [ ]:
test_job

company_name                        Smart Food Safe Solutions Inc
job_title                             Software Testing Internship
Unnamed: 2                                                      -
job_des         Selected intern's day-to-day responsibilities ...
job_location                                            Bengaluru
exp_req                                                         0
edu_req         students or freshers can apply who: are availa...
cert_req                                                        -
test             selected interns day to day responsibilities ...
Name: 0, dtype: object

In [ ]:
data_lower = []
for s in test_job['job_des']:
    data_lower.append(s.lower())

test_job_des = ""
test_job_des = test_job_des.join(data_lower)
j=1
for i in test_job_des:
  if j%40:
    print(i, end='')
  else:
    print(i)
  j = j+1

selected intern's day-to-day responsibil
ities include: 1. reviewing software req
uirements and preparing test cases 2. ex
ecute test cases (manual or automated) a
nd analyze results 3. evaluate product c
ode according to specifications 4. repor
t bugs and errors to development teams. 
skills req: basic knowledge of database/
sql;knowledge of any scripting language 
like vbscript, javascript, c#, shell/per
l scripting

In [ ]:
v = CountVectorizer()

v = CountVectorizer(ngram_range=(1,2))
v.fit([test_job_des])
print(type(v.vocabulary_))
print(len(v.vocabulary_))
v.vocabulary_

<class 'dict'>
95


{'selected': 73,
 'intern': 36,
 'day': 23,
 'to': 89,
 'responsibilities': 65,
 'include': 34,
 'reviewing': 69,
 'software': 79,
 'requirements': 63,
 'and': 4,
 'preparing': 55,
 'test': 87,
 'cases': 16,
 'execute': 32,
 'manual': 46,
 'or': 51,
 'automated': 10,
 'analyze': 2,
 'results': 67,
 'evaluate': 30,
 'product': 57,
 'code': 19,
 'according': 0,
 'specifications': 81,
 'report': 59,
 'bugs': 14,
 'errors': 28,
 'development': 26,
 'teams': 85,
 'skills': 77,
 'req': 61,
 'basic': 12,
 'knowledge': 40,
 'of': 48,
 'database': 21,
 'sql': 83,
 'any': 8,
 'scripting': 71,
 'language': 42,
 'like': 44,
 'vbscript': 93,
 'javascript': 38,
 'shell': 75,
 'perl': 53,
 'selected intern': 74,
 'intern day': 37,
 'day to': 25,
 'to day': 90,
 'day responsibilities': 24,
 'responsibilities include': 66,
 'include reviewing': 35,
 'reviewing software': 70,
 'software requirements': 80,
 'requirements and': 64,
 'and preparing': 7,
 'preparing test': 56,
 'test cases': 88,
 'cases exe

In [ ]:
tf_count = v.transform(resumes['test'])
tf_ud = tf_count.toarray()
print(type(tf_count))
print(tf_ud.shape)
print(tf_ud)

<class 'scipy.sparse.csr.csr_matrix'>
(21, 95)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
nbrs = NearestNeighbors(n_neighbors=3, n_jobs=-1).fit(tf_count)

In [ ]:
def getNearestN(query):
  q_tf_count = v.transform(query)
  distances, indices = nbrs.kneighbors(q_tf_count)
  return distances, indices

In [ ]:
distances, indices = getNearestN([test_job_des])

In [ ]:
len(distances[0])

3

In [ ]:
print("Distances          ", "Indices")
for i in range(0,len(distances[0])):
  print(distances[0][i],"    ", indices[0][i])

Distances           Indices
11.045361017187261      17
11.180339887498949      19
11.445523142259598      16


In [ ]:
type(indices)
for i in indices:
    rec_jobs = resumes.iloc[i] 
rec_jobs

name                            email mobile_number  \
17   Lavanya  lavanya.adhinarayanan@gmail.com     988403855   
20     Aneet           aneetatomy23@gmail.com    8129945395   
16  Sireesha        karakondavenkat@gmail.com    9182382214   

                                               skills  \
17  ['Sports', 'Engineering', 'Scrum', 'Payments',...   
20  ['Engineering', 'Windows', 'Java', 'Social med...   
16  ['Scripting', 'Java', 'Oracle', 'Windows', 'Sq...   

                                college_name                      degree  \
17  Dayal Singh College, University of Delhi                  B.Sc. Hons   
20                           NSIT, New Delhi  B.Tech (Computer Science)    
16                                IIT Madras                         NaN   

   designation                                         experience  \
17         NaN  ['▪', '▪ Worked with Insoft.com Private Ltd, C...   
20         NaN  ['PageMe Consultancy [Digital Marketing Analys...   
16         NaN                                                NaN   

   company_names  no_of_pages  total_experience  \
17           NaN          9.0              0.00   
20           NaN          2.0              0.25   
16           NaN          2.0              0.00   

                                                 test  
17   sports engineering scrum payments erp windows...  
20   engineering windows java social media hotel c...  
16   scripting java oracle windows sql english css...

# JOB TO JOB MATCHING

In [ ]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 33
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   company_name  34 non-null     object
 1   job_title     34 non-null     object
 2   Unnamed: 2    23 non-null     object
 3   job_des       34 non-null     object
 4   job_location  34 non-null     object
 5   exp_req       16 non-null     object
 6   edu_req       11 non-null     object
 7   cert_req      3 non-null      object
 8   test          34 non-null     object
dtypes: object(9)
memory usage: 2.7+ KB


In [ ]:
jobs.head()

company_name                           job_title  \
0  Smart Food Safe Solutions Inc         Software Testing Internship   
1                       Mobiveil           Embedded Software Testing   
2     Open Systems International  Senior Engineer - Software Testing   
3           HyperLink InfoSystem        Business Development Manager   
4                        Infosys        Oracle Functional Consultant   

  Unnamed: 2                                            job_des job_location  \
0          -  Selected intern's day-to-day responsibilities ...    Bengaluru   
1          -  Good in different type of testing and proficie...    Bangalore   
2          -  Specific on-the-job training will be provided....    Bengaluru   
3          -  Contacting potential clients to establish rapp...    Ahemdabad   
4          -  Able to configure financial modules independen...    Mangalore   

                                             exp_req  \
0                                                  0   
1                                           4+ Years   
2  Strong hands-on 2+ years’ experience on Test...   
3                                           2+ years   
4                                5 to 8 years of exp   

                                             edu_req  \
0  students or freshers can apply who: are availa...   
1                                         Btech/ MCA   
2  Master’s degree in Computer Science, Softwar...   
3  Any graduation/post graduation, MBA/PGDM in Ma...   
4                                                NaN   

                                            cert_req  \
0                                                  -   
1            should own a module/component end 2 end   
2  Experience with Quality Assurance within an Ag...   
3                                                NaN   
4                                                NaN   

                                                test  
0   selected interns day to day responsibilities ...  
1   good in different type of testing and profici...  
2   specific on the job training will be provided...  
3   contacting potential clients to establish rap...  
4   able to configure financial modules independe...

In [ ]:
jobs = jobs[jobs['job_des'].notna()]
jobs.shape

(34, 9)

In [ ]:
jobs['job_des']

0     Selected intern's day-to-day responsibilities ...
1     Good in different type of testing and proficie...
2     Specific on-the-job training will be provided....
3     Contacting potential clients to establish rapp...
4     Able to configure financial modules independen...
5     As a data analyst, design and carry out survey...
6     IT/systems associate analyst participates in t...
7     As a business analyst, use data modelling tech...
8     Understanding business objectives and developi...
9     Responsibilities include: Identify valuable da...
10    Require Strong Development & Test Resources fo...
11    An Associate Developer works with and supports...
12    The data scientist job description involves fe...
13    As a data analyst, develop records management ...
14    NLP, Machine Learning, with Java as operating ...
15    Perform following duties: oversee the implemen...
16    The hire is expected to have good knowledge of...
17    Perform following duties: creating documen

In [ ]:
# CREATING A BAG OF WORDS

from sklearn.feature_extraction.text import TfidfVectorizer

# Convert a collection of raw documents to a matrix of TF-IDF features.
# tf-idf means term-frequency times inverse document-frequency
# tf-idf for a term t of a document d in a document set is tf-idf(t, d) = tf(t, d) * idf(t)
# idf is computed as idf(t) = log [ n / df(t) ] + 1 

tdif = TfidfVectorizer(stop_words='english')
# print(type(tdif))
tdif_matrix = tdif.fit_transform(jobs['job_des'])
tdif_matrix.shape

(34, 629)

In [ ]:
print(type(tdif_matrix))

<class 'scipy.sparse._csr.csr_matrix'>


In [ ]:
from sklearn.metrics.pairwise import linear_kernel

# considers not only the similarity between vectors under the same dimension,
# but also across dimensions. When used in machine learning algorithms, 
# this allows to account for feature interaction.

cosine_sim = linear_kernel(tdif_matrix, tdif_matrix)

#  tf-idf functionality in sklearn.feature_extraction.text can produce normalized vectors, in which case cosine_similarity is equivalent to linear_kernel, only slower

indices = pd.Series(jobs.index, index=jobs['job_title']).drop_duplicates()
indices

job_title
Software Testing Internship                            0
Embedded Software Testing                              1
Senior Engineer - Software Testing                     2
Business Development Manager                           3
Oracle Functional Consultant                           4
Jr. Data Analyst                                       5
IT/System Associate Analyst                            6
Senior Business Analyst                                7
Machine Learning Engineer                              8
Data Scientist                                         9
Software Testing Engineer                             10
Associate Developer                                   11
Data Scientist                                        12
Data Analyst                                          13
NLP / Machine Learning                                14
Business Analyst                                      15
Java GCP Data Engineer                                16
Jr. Business Analyst 

In [ ]:
def get_recommendations(title,cosine_sim=cosine_sim):
  idx = indices[title]
  # print(idx)
  sim_scores = list(enumerate(cosine_sim[idx]))
  # print(sim_scores)
  sim_scores = sorted(sim_scores, key=lambda X:X[1], reverse=True)
  # we don't how this 'key=lambda X:X[1]' works
  # print(sim_scores)
  sim_scores = sim_scores[0:5]

  tech_indices = [i[0] for i in sim_scores]
  return jobs.iloc[tech_indices]

In [ ]:
sim_jobs = get_recommendations('Software Testing Internship')
sim_jobs

company_name                           job_title  \
0   Smart Food Safe Solutions Inc         Software Testing Internship   
28          Hexaware Technologies           Software Testing Engineer   
2      Open Systems International  Senior Engineer - Software Testing   
32                          Cvent           Software Testing Engineer   
10                          Wipro           Software Testing Engineer   

   Unnamed: 2                                            job_des job_location  \
0           -  Selected intern's day-to-day responsibilities ...    Bengaluru   
28          -  Day-to-day responsibilities include: 1. Review...  Navi Mumbai   
2           -  Specific on-the-job training will be provided....    Bengaluru   
32          -  To ensure success as a software test engineer,...   West Delhi   
10          -  Require Strong Development & Test Resources fo...       Mumbai   

                                              exp_req  \
0                                                   0   
28                                                NaN   
2   Strong hands-on 2+ years’ experience on Test...   
32  Experience working with popular operating syst...   
10                                                NaN   

                                              edu_req  \
0   students or freshers can apply who: are availa...   
28                                                NaN   
2   Master’s degree in Computer Science, Softwar...   
32  Bachelor’s degree in computer science, softwar...   
10                                                NaN   

                                             cert_req  \
0                                                   -   
28                                                NaN   
2   Experience with Quality Assurance within an Ag...   
32                                                NaN   
10                                                NaN   

                                                 test  
0    selected interns day to day responsibilities ...  
28   day to day responsibilities include: 1 review...  
2    specific on the job training will be provided...  
32   to ensure success as a software test engineer...  
10   require strong development and test resources...

# RESUME TO RESUME MATCHING

In [ ]:
resumes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              21 non-null     object 
 1   email             21 non-null     object 
 2   mobile_number     21 non-null     object 
 3   skills            21 non-null     object 
 4   college_name      3 non-null      object 
 5   degree            13 non-null     object 
 6   designation       5 non-null      object 
 7   experience        13 non-null     object 
 8   company_names     2 non-null      object 
 9   no_of_pages       21 non-null     float64
 10  total_experience  21 non-null     float64
dtypes: float64(2), object(9)
memory usage: 2.0+ KB


In [ ]:
resumes.head()

name                       email mobile_number  \
0     Lakshay Yadav  lakshay.mcs21.du@gmail.com    7982993455   
1  STUTI EDUCATION-      stuti.agg.16@gmail.com    8950764441   
2     KARAMJOT KAUR       karamjotk03@gmail.com    9654226396   
3    RITIKA MOHANTY   ritikamohanty38@gmail.com    9540643304   
4     Email Contact       tupeamruta7@gmail.com    7249864331   

                                              skills college_name  \
0  ['Engineering', 'Java', 'Tensorflow', 'Researc...          NaN   
1  ['Digital marketing', 'Excel', 'Photoshop', 'P...          NaN   
2  ['Engineering', 'Java', 'Database', 'Documenta...          NaN   
3  ['Php', 'Computer science', 'Java', 'Website',...          NaN   
4                          ['English', 'Email', 'C']          NaN   

                                              degree  \
0  ['Department of Computer Science', 'Bachelor’s...   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                ['Degree', 'BCOM.']   

                                         designation  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  ['Machine Learning (Self-Paced) \nBy: Stanford...   
4                                                NaN   

                                          experience company_names  \
0                                                NaN           NaN   
1  ['real case study.', 'Achievements-', '➢  Cert...           NaN   
2                                                NaN           NaN   
3  ['Part-time Content Writer, Weblink.In', 'May ...           NaN   
4                                                NaN           NaN   

   no_of_pages  total_experience  
0          1.0              0.00  
1          2.0              0.00  
2          2.0              0.00  
3          1.0              0.75  
4          2.0              0.00

In [ ]:
resumes = resumes[resumes['skills'].notna()]
resumes.shape

(21, 11)

In [ ]:
resumes['test']

0      engineering java tensorflow research python o...
1      digital marketing excel photoshop python mark...
2      engineering java database documentation softw...
3      php computer science java website presentatio...
4                                      english email c 
5      data analytics seaborn matplotlib pandas pyth...
6      mysql purchasing windows tableau linux schedu...
7      design certification engineering process emai...
8      policies updates mysql engineering forecastin...
9      java email html technical newspaper english c...
10     salesforce finance mis seo website design crm...
11     php training mysql java engineering proposal ...
12     mysql vendors engineering distribution querie...
13     excel mysql engineering analytics sales pytho...
14     c html technical javascript english administr...
15     mechanical engineering reporting research tec...
16     scripting java oracle windows sql english css...
17     sports engineering scrum payments erp win

In [ ]:
# CREATING A BAG OF WORDS

from sklearn.feature_extraction.text import TfidfVectorizer

# Convert a collection of raw documents to a matrix of TF-IDF features.
# tf-idf means term-frequency times inverse document-frequency
# tf-idf for a term t of a document d in a document set is tf-idf(t, d) = tf(t, d) * idf(t)
# idf is computed as idf(t) = log [ n / df(t) ] + 1 

tdif = TfidfVectorizer(stop_words='english')
# print(type(tdif))
tdif_matrix = tdif.fit_transform(resumes['test'])
tdif_matrix.shape

(21, 167)

In [ ]:
print(type(tdif_matrix))

<class 'scipy.sparse.csr.csr_matrix'>


In [ ]:
from sklearn.metrics.pairwise import linear_kernel

# considers not only the similarity between vectors under the same dimension,
# but also across dimensions. When used in machine learning algorithms, 
# this allows to account for feature interaction.

cosine_sim = linear_kernel(tdif_matrix, tdif_matrix)

#  tf-idf functionality in sklearn.feature_extraction.text can produce 
# normalized vectors, in which case cosine_similarity is equivalent to
#  linear_kernel, only slower

indices = pd.Series(resumes.index, index=resumes['name']).drop_duplicates()
indices

name
Lakshay Yadav                      0
STUTI                              1
KARAMJOT KAUR                      2
RITIKA MOHANTY                     3
Email Contact                      4
Akash Shetty                       5
ANURAG CHAUHAN                     6
R.Vimalraj EDUCATION               7
Avi Sharma                         8
RESUME SATYAJIT                    9
BL Karnataka                      10
Ansari                            11
JJ COLLEGE OF ARTS AND SCIENCE    12
KISHORE KUMAR                     13
KRISHNA PRABU                     14
PRASAD Digital                    15
Sireesha                          16
Lavanya                           17
Rohan                             19
Aneet                             20
 Himani                           21
dtype: int64

In [ ]:
def get_recommendations(title,cosine_sim=cosine_sim):
  idx = indices[title]
  # print(idx)
  sim_scores = list(enumerate(cosine_sim[idx]))
  # print(sim_scores)
  sim_scores = sorted(sim_scores, key=lambda X:X[1], reverse=True)
  # we don't how this 'key=lambda X:X[1]' works
  # print(sim_scores)
  sim_scores = sim_scores[1:4]

  tech_indices = [i[0] for i in sim_scores]
  return resumes.iloc[tech_indices]

In [ ]:
sim_res = get_recommendations('Lakshay Yadav')
sim_res

name                       email mobile_number  \
2   KARAMJOT KAUR       karamjotk03@gmail.com    9654226396   
10   BL Karnataka      Varunbl.vrun@gmail.com       1767605   
11         Ansari  ansarialiasgar40@gmail.com    9779811193   

                                               skills college_name  \
2   ['Engineering', 'Java', 'Database', 'Documenta...          NaN   
10  ['Salesforce', 'Finance', 'Mis', 'Seo', 'Websi...          NaN   
11  ['Php', 'Training', 'Mysql', 'Java', 'Engineer...          NaN   

                                        degree  \
2                                          NaN   
10                                         NaN   
11  ['BE in Computer Science and Engineering']   

                                     designation  \
2                                            NaN   
10  ['Bot Developer', 'Data Processing Analyst']   
11                           ['Playing Cricket']   

                                           experience  company_names  \
2                                                 NaN            NaN   
10  ['Data Processing Analyst', 'NielsenIQ', 'Oct ...  ['Microsoft']   
11              ['15-Sep-', '2021 - 19-', 'Oct-2021']            NaN   

    no_of_pages  total_experience  \
2           2.0              0.00   
10          2.0              1.42   
11          1.0              0.00   

                                                 test  
2    engineering java database documentation softw...  
10   salesforce finance mis seo website design crm...  
11   php training mysql java engineering proposal ...

# COLABORATIVE FILTERING

In [ ]:
sim_res['test']

2      engineering java database documentation softw...
10     salesforce finance mis seo website design crm...
11     php training mysql java engineering proposal ...
Name: test, dtype: object

In [ ]:
sim_skills = ""
for res in sim_res['test']:
  sim_skills = sim_skills +" "+ res

sim_skills

'  engineering java database documentation software engineering sql communication system technical c++ html computer science time management english css   salesforce finance mis seo website design crm computer science data analytics reporting excel research migration process procurement training automation ui certification data analysis python analytics analysis security   php training mysql java engineering proposal technical computer science english html5 system '

In [ ]:
v = CountVectorizer()

v = CountVectorizer(ngram_range=(1,2))
v.fit([sim_skills])
print(type(v.vocabulary_))
print(len(v.vocabulary_))
v.vocabulary_

<class 'dict'>
95


{'engineering': 27,
 'java': 42,
 'database': 21,
 'documentation': 25,
 'software': 77,
 'sql': 79,
 'communication': 10,
 'system': 81,
 'technical': 83,
 'html': 38,
 'computer': 12,
 'science': 69,
 'time': 86,
 'management': 45,
 'english': 31,
 'css': 16,
 'salesforce': 67,
 'finance': 36,
 'mis': 49,
 'seo': 75,
 'website': 93,
 'design': 23,
 'crm': 14,
 'data': 18,
 'analytics': 3,
 'reporting': 63,
 'excel': 34,
 'research': 65,
 'migration': 47,
 'process': 55,
 'procurement': 57,
 'training': 88,
 'automation': 6,
 'ui': 91,
 'certification': 8,
 'analysis': 0,
 'python': 61,
 'security': 73,
 'php': 53,
 'mysql': 51,
 'proposal': 59,
 'html5': 40,
 'engineering java': 28,
 'java database': 43,
 'database documentation': 22,
 'documentation software': 26,
 'software engineering': 78,
 'engineering sql': 30,
 'sql communication': 80,
 'communication system': 11,
 'system technical': 82,
 'technical html': 85,
 'html computer': 39,
 'computer science': 13,
 'science time': 72

In [ ]:
tf_count = v.transform(jobs['test'])
tf_ud = tf_count.toarray()
print(type(tf_count))
print(tf_ud.shape)
print(tf_ud)

<class 'scipy.sparse.csr.csr_matrix'>
(34, 95)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
nbrs = NearestNeighbors(n_neighbors=5, n_jobs=-1).fit(tf_count)

In [ ]:
def getNearestN(query):
  q_tf_count = v.transform(query)
  distances, indices = nbrs.kneighbors(q_tf_count)
  return distances, indices

In [ ]:
distances, indices = getNearestN([jobseeker_skills])

In [ ]:
print("Distances          ", "Indices")
for i in range(1,len(distances[0])):
  print(distances[0][i],"    ", indices[0][i])

Distances           Indices
1.0      0
1.0      14
1.0      28
1.4142135623730951      19


TOP N JOBS RECOMMENDED TO LAKSHAY YADAV USING COLLABORATIVE FILTERING

In [ ]:
type(indices)
for i in indices:
    rec_jobs = jobs[['job_title', 'company_name','job_location']].iloc[i] 
rec_jobs

job_title  \
25  Associate Developer (Python with Machine Learn...   
0                         Software Testing Internship   
14                             NLP / Machine Learning   
28                          Software Testing Engineer   
19               Microsoft Technology Project Manager   

                          company_name job_location  
25                           Capgemini         Pune  
0        Smart Food Safe Solutions Inc    Bengaluru  
14  Oracle Financial Services Software         Pune  
28               Hexaware Technologies  Navi Mumbai  
19                   AD Infosystem.LLC        Delhi